AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Name: "DelaySayAPI"
  Function:
    Timeout: 300

Resources:
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: User
  DelaySayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-slash-command/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.7
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref UserTable
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref UserTable
      Events:
        DelaySay:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /delaysay
            Method: ANY
  DelaySayUserAuthenticationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-user-authentication/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.7
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref UserTable
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref UserTable
      Events:
        DelaySayUserAuthentication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /delaysay-user-authentication
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DelaySayApi:
    Description: "API Gateway endpoint URL for Prod stage for DelaySay function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delaysay/"
  UserTable:
    Description: "DelaySay DynamoDB Table ARN"
    Value: !GetAtt UserTable.Arn
  DelaySayFunction:
    Description: "DelaySay Lambda Function ARN"
    Value: !GetAtt DelaySayFunction.Arn
  DelaySayUserAuthenticationFunction:
    Description: "DelaySay User Authentication Lambda Function ARN"
    Value: !GetAtt DelaySayUserAuthenticationFunction.Arn
  DelaySayFunctionIamRole:
    Description: "Implicit IAM Role created for DelaySay function"
    Value: !GetAtt DelaySayFunctionRole.Arn
  DelaySayUserAuthenticationFunctionIamRole:
    Description: "Implicit IAM Role created for DelaySay user auth function"
    Value: !GetAtt DelaySayUserAuthenticationFunctionRole.Arn
