AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DelaySay SAM template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # Set the timeout to 5 minutes (300 seconds) just in case!
    # That way the Lambda (hopefully) doesn't silently time out
    # and leave the user wondering what happened.
    Timeout: 300
    MemorySize: 1792

Parameters:
  SlashCommand:
    Type: String
    Description: "Slash command to run the Slack app (like '/delay')"
  SlashCommandLinksDomain:
    Type: String
    Description: "Domain to send users to when responding to their commands"
  ContactPage:
    Type: String
    Description: "URL for your app's contact page"
  SupportEmail:
    Type: String
    Description: "Support email for your app"
  DelaySayTableName:
    Type: String
    Description: "Name for the DelaySay DynamoDB table"
  DelaySayApiDomain:
    Type: String
    Description: "Domain name for the DelaySay API endpoint (api.example.com)"
  DelaySayDomain:
    Type: String
    Description: "Root domain name for DelaySay (example.com)"
  SlackOAuthUrl:
    Type: String
    Description: "Install URL (slack.com/oauth/authorize...)"
  
  BillingPortalFailUrl:
    Type: String
    Description: "Apology page for invalid/expired billing tokens"
  InstallSuccessUrl:
    Type: String
    Description: "Congrats page for successful installation"
  InstallCancelUrl:
    Type: String
    Description: "Apology page for canceled installation"
  InstallFailUrl:
    Type: String
    Description: "Apology page for failed installation"
  SubscribeUrl:
    Type: String
    Description: "Page that redirects user to Stripe checkout"
  
  StripeCheckoutSigningSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe checkout webhook signing secret"
  StripeTestingCheckoutSigningSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe checkout webhook signing secret (testing version)"
  StripeApiKeySsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe API key"
  StripeTestingApiKeySsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe API key (testing version)"
  SlackSigningSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Slack signing secret"
  SlackClientIdSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Slack client ID"
  SlackClientSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Slack client secret"
  KmsMasterKeyArn:
    Type: String
    Description: "KMS key ARN for encrypting Slack users' OAuth tokens"

Resources:
  
  # Layers
  DelaySayLayerExceptions:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-exceptions/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
  DelaySayLayerStripeSubscription:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-stripe-subscription/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
  DelaySayLayerTeam:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-team/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
  DelaySayLayerUser:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-user/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
  DelaySayLayerBillingToken:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-billing-token/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
  
  # Website
  DelaySayApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DelaySayApiDomain
      ValidationMethod: DNS
  DelaySayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Domain:
        # Note: Any changes to the API domain or Lambda event paths
        # can take 15 or more minutes to finish updating. Until then,
        # slash commands may fail with an "http_client_error" and
        # user auth may fail with "Missing Authentication Token".
        # Also, if the API domain changes, navigate to the ACM console
        # and create a Route 53 record as described in README.md
        DomainName: !Ref DelaySayApiDomain
        CertificateArn: !Ref DelaySayApiCertificate
        Route53:
          HostedZoneName: !Sub "${DelaySayDomain}."
  DelaySayInstallRedirectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-redirect-install/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.10
      Environment:
        Variables:
          SLACK_OAUTH_URL: !Ref SlackOAuthUrl
      Events:
        DelaySayInstallRedirect:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /add
            Method: ANY
            RestApiId: !Ref DelaySayApi
  DelaySayBillingRedirectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-redirect-stripe-customer-portal/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.10
      Layers:
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerTeam
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerBillingToken
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          BILLING_PORTAL_FAIL_URL: !Ref BillingPortalFailUrl
          REDIRECT_URL_AFTER_PORTAL: !Sub "https://${DelaySayDomain}/"
          AUTH_TABLE_NAME: !Ref DelaySayTable
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
      Events:
        DelaySayBillingRedirect:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /billing
            Method: ANY
            RestApiId: !Ref DelaySayApi
  
  # DynamoDB
  DelaySayTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: !Ref DelaySayTableName
  
  # Lambda functions
  DelaySaySecondResponderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-slash-command-second-responder/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.10
      Layers:
        # Note: Only 5 layers/function allowed,
        # so combine if need to add more classes
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerTeam
        - !Ref DelaySayLayerUser
        - !Ref DelaySayLayerBillingToken
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref DelaySayTable
          KMS_MASTER_KEY_ARN: !Ref KmsMasterKeyArn
          SLACK_SIGNING_SECRET_SSM_NAME: !Sub "/${SlackSigningSecretSsmName}"
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
          SLASH_COMMAND: !Ref SlashCommand
          SLASH_COMMAND_LINKS_DOMAIN: !Ref SlashCommandLinksDomain
          SUBSCRIBE_URL: !Ref SubscribeUrl
          CONTACT_PAGE: !Ref ContactPage
          SUPPORT_EMAIL: !Ref SupportEmail
  DelaySayFirstResponderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-slash-command-first-responder/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.10
      Layers:
        - !Ref DelaySayLayerExceptions
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref DelaySaySecondResponderFunction
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackSigningSecretSsmName
      Environment:
        Variables:
          SECOND_RESPONDER_FUNCTION: !GetAtt DelaySaySecondResponderFunction.Arn
          SLACK_SIGNING_SECRET_SSM_NAME: !Sub "/${SlackSigningSecretSsmName}"
          SLASH_COMMAND: !Ref SlashCommand
          CONTACT_PAGE: !Ref ContactPage
          SUPPORT_EMAIL: !Ref SupportEmail
      Events:
        DelaySay:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slash-command
            Method: ANY
            RestApiId: !Ref DelaySayApi
  DelaySayUserAuthorizationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-user-authorization/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.10
      Layers:
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerTeam
        - !Ref DelaySayLayerUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackClientIdSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackClientSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref DelaySayTable
          KMS_MASTER_KEY_ARN: !Ref KmsMasterKeyArn
          SLACK_CLIENT_ID_SSM_NAME: !Sub "/${SlackClientIdSsmName}"
          SLACK_CLIENT_SECRET_SSM_NAME: !Sub "/${SlackClientSecretSsmName}"
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
          INSTALL_SUCCESS_URL: !Ref InstallSuccessUrl
          INSTALL_CANCEL_URL: !Ref InstallCancelUrl
          INSTALL_FAIL_URL: !Ref InstallFailUrl
      Events:
        DelaySayUserAuthorization:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user-authorization
            Method: ANY
            RestApiId: !Ref DelaySayApi
  DelaySayStripeCheckoutWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-stripe-checkout-webhook/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.10
      Layers:
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerTeam
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeCheckoutSigningSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingCheckoutSigningSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref DelaySayTable
          STRIPE_CHECKOUT_SIGNING_SECRET_SSM_NAME: !Sub "/${StripeCheckoutSigningSecretSsmName}"
          STRIPE_TESTING_CHECKOUT_SIGNING_SECRET_SSM_NAME: !Sub "/${StripeTestingCheckoutSigningSecretSsmName}"
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
      Events:
        DelaySayStripeCheckout:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stripe-checkout-webhook
            Method: ANY
            RestApiId: !Ref DelaySayApi

Outputs:
  DelaySayApi:
    Description: "API Gateway endpoint URL for Prod stage for DelaySay function"
    Value: !Ref DelaySayApiDomain
  DelaySayInstallRedirectFunction:
    Description: "DelaySay Slack Install Redirect Lambda Function ARN"
    Value: !GetAtt DelaySayInstallRedirectFunction.Arn
  DelaySayTable:
    Description: "DelaySay DynamoDB Table ARN"
    Value: !GetAtt DelaySayTable.Arn
  DelaySayFirstResponderFunction:
    Description: "DelaySay First Responder Lambda Function ARN"
    Value: !GetAtt DelaySayFirstResponderFunction.Arn
  DelaySaySecondResponderFunction:
    Description: "DelaySay Second Responder Lambda Function ARN"
    Value: !GetAtt DelaySaySecondResponderFunction.Arn
  DelaySayUserAuthorizationFunction:
    Description: "DelaySay User Authorization Lambda Function ARN"
    Value: !GetAtt DelaySayUserAuthorizationFunction.Arn
  DelaySayStripeCheckoutWebhookFunction:
    Description: "DelaySay Stripe Checkout Lambda Function ARN"
    Value: !GetAtt DelaySayStripeCheckoutWebhookFunction.Arn
  DelaySayFirstResponderFunctionIamRole:
    Description: "Implicit IAM Role created for one DelaySay function"
    Value: !GetAtt DelaySayFirstResponderFunctionRole.Arn
  DelaySaySecondResponderFunctionIamRole:
    Description: "Implicit IAM Role created for other DelaySay function"
    Value: !GetAtt DelaySaySecondResponderFunctionRole.Arn
  DelaySayUserAuthorizationFunctionIamRole:
    Description: "Implicit IAM Role created for DelaySay user auth function"
    Value: !GetAtt DelaySayUserAuthorizationFunctionRole.Arn
