AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DelaySayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: delaysay/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        DelaySay:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /delaysay
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DelaySayApi:
    Description: "API Gateway endpoint URL for Prod stage for DelaySay function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delaysay/"
  DelaySayFunction:
    Description: "DelaySay Lambda Function ARN"
    Value: !GetAtt DelaySayFunction.Arn
  DelaySayFunctionIamRole:
    Description: "Implicit IAM Role created for DelaySay function"
    Value: !GetAtt DelaySayFunctionRole.Arn
