AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DelaySay SAM template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 1792

Parameters:
  DelaySayApiDomain:
    Type: String
    Description: "Domain name for the DelaySay API endpoint (api.example.com)"
  DelaySayDomain:
    Type: String
    Description: "Root domain name for DelaySay (example.com)"
  SlackOAuthUrl:
    Type: String
    Description: "Install URL (slack.com/oauth/authorize...)"
  StripeCheckoutSigningSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe checkout webhook signing secret"
  StripeTestingCheckoutSigningSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe checkout webhook signing secret (testing version)"
  StripeApiKeySsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe API key"
  StripeTestingApiKeySsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Stripe API key (testing version)"
  SlackSigningSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Slack signing secret"
  SlackClientIdSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Slack client ID"
  SlackClientSecretSsmName:
    Type: String
    Description: "SSM Parameter Store parameter name for Slack client secret"
  KmsMasterKeyArn:
    Type: String
    Description: "KMS key ARN for encrypting Slack users' OAuth tokens"

Resources:
  
  # Layers
  DelaySayLayerExceptions:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-exceptions/
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
  DelaySayLayerStripeSubscription:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-stripe-subscription/
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
  DelaySayLayerTeam:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-team/
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
  DelaySayLayerUser:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: code-class-user/
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
  
  # Website
  DelaySayApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DelaySayApiDomain
      ValidationMethod: DNS
  DelaySayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Domain:
        # Note: Any changes to the API domain or Lambda event paths
        # can take 15 or more minutes to finish updating. Until then,
        # slash commands may fail with an "http_client_error" and
        # user auth may fail with "Missing Authentication Token".
        # Also, if the API domain changes, navigate to the ACM console
        # and create a Route 53 record as described in README.md
        DomainName: !Ref DelaySayApiDomain
        CertificateArn: !Ref DelaySayApiCertificate
        Route53:
          HostedZoneName: !Sub "${DelaySayDomain}."
  DelaySayInstallRedirectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-install-redirect/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.8
      Environment:
        Variables:
          SLACK_OAUTH_URL: !Ref SlackOAuthUrl
      Events:
        DelaySayInstallRedirect:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /add
            Method: ANY
            RestApiId: !Ref DelaySayApi
  
  # DynamoDB
  DelaySayTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: DelaySay
  
  # Lambda functions
  DelaySayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-slash-command/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.8
      Layers:
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerTeam
        - !Ref DelaySayLayerUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackSigningSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref DelaySayTable
          KMS_MASTER_KEY_ARN: !Ref KmsMasterKeyArn
          SLACK_SIGNING_SECRET_SSM_NAME: !Sub "/${SlackSigningSecretSsmName}"
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
      Events:
        DelaySay:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slash-command
            Method: ANY
            RestApiId: !Ref DelaySayApi
  DelaySayUserAuthorizationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-user-authorization/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.8
      Layers:
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerTeam
        - !Ref DelaySayLayerUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackClientIdSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackClientSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref DelaySayTable
          KMS_MASTER_KEY_ARN: !Ref KmsMasterKeyArn
          SLACK_CLIENT_ID_SSM_NAME: !Sub "/${SlackClientIdSsmName}"
          SLACK_CLIENT_SECRET_SSM_NAME: !Sub "/${SlackClientSecretSsmName}"
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
      Events:
        DelaySayUserAuthorization:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user-authorization
            Method: ANY
            RestApiId: !Ref DelaySayApi
  DelaySayStripeCheckoutWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code-slack-stripe-checkout-webhook/
      Handler: app.lambda_handler_with_catch_all
      Runtime: python3.8
      Layers:
        - !Ref DelaySayLayerExceptions
        - !Ref DelaySayLayerStripeSubscription
        - !Ref DelaySayLayerTeam
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DelaySayTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeCheckoutSigningSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingCheckoutSigningSecretSsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeApiKeySsmName
        - SSMParameterReadPolicy:
            ParameterName: !Ref StripeTestingApiKeySsmName
      Environment:
        Variables:
          AUTH_TABLE_NAME: !Ref DelaySayTable
          STRIPE_CHECKOUT_SIGNING_SECRET_SSM_NAME: !Sub "/${StripeCheckoutSigningSecretSsmName}"
          STRIPE_TESTING_CHECKOUT_SIGNING_SECRET_SSM_NAME: !Sub "/${StripeTestingCheckoutSigningSecretSsmName}"
          STRIPE_API_KEY_SSM_NAME: !Sub "/${StripeApiKeySsmName}"
          STRIPE_TESTING_API_KEY_SSM_NAME: !Sub "/${StripeTestingApiKeySsmName}"
      Events:
        DelaySayStripeCheckout:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stripe-checkout-webhook
            Method: ANY
            RestApiId: !Ref DelaySayApi

Outputs:
  DelaySayApi:
    Description: "API Gateway endpoint URL for Prod stage for DelaySay function"
    Value: !Ref DelaySayApiDomain
  DelaySayInstallRedirectFunction:
    Description: "DelaySay Slack Install Redirect Lambda Function ARN"
    Value: !GetAtt DelaySayInstallRedirectFunction.Arn
  DelaySayTable:
    Description: "DelaySay DynamoDB Table ARN"
    Value: !GetAtt DelaySayTable.Arn
  DelaySayFunction:
    Description: "DelaySay Lambda Function ARN"
    Value: !GetAtt DelaySayFunction.Arn
  DelaySayUserAuthorizationFunction:
    Description: "DelaySay User Authorization Lambda Function ARN"
    Value: !GetAtt DelaySayUserAuthorizationFunction.Arn
  DelaySayStripeCheckoutWebhookFunction:
    Description: "DelaySay Stripe Checkout Lambda Function ARN"
    Value: !GetAtt DelaySayStripeCheckoutWebhookFunction.Arn
  DelaySayFunctionIamRole:
    Description: "Implicit IAM Role created for DelaySay function"
    Value: !GetAtt DelaySayFunctionRole.Arn
  DelaySayUserAuthorizationFunctionIamRole:
    Description: "Implicit IAM Role created for DelaySay user auth function"
    Value: !GetAtt DelaySayUserAuthorizationFunctionRole.Arn
